# Generated by Django 5.2 on 2025-07-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
