# Generated by Django 5.2 on 2025-07-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
